file_info= {

    "component-versions.rst": ("Component versions", "https://discourse.ubuntu.com/t/component-versions/21413", "anbox/landing.rst", 5),
    "index.rst": ("Anbox Cloud documentation", "https://discourse.ubuntu.com/t/anbox-cloud-documentation/17029", "na", 0),
    "manage-addons.rst": ("Create addons", "https://discourse.ubuntu.com/t/managing-addons/17759", "howto/manage/landing.rst", 3),
    "release-notes.rst": ("Release notes", "https://discourse.ubuntu.com/t/release-notes/17842", "anbox/landing.rst", 2),
    "requirements.rst": ("Requirements", "https://discourse.ubuntu.com/t/installation-requirements/17734", "anbox/landing.rst", 1),
    "roadmap.rst": ("Release roadmap", "https://discourse.ubuntu.com/t/release-roadmap/19359", "anbox/landing.rst", 3),
    "supported-versions.rst": ("Supported versions", "https://discourse.ubuntu.com/t/supported-versions/21046", "anbox/landing.rst", 4),
    "explanation/aar.rst": ("About the AAR", "https://discourse.ubuntu.com/t/application-registry/17761", "explanation/landing.rst", 4),
    "explanation/ams.rst": ("About AMS", "https://discourse.ubuntu.com/t/about-ams/24321", "explanation/landing.rst", 2),
    "explanation/anbox-cloud.rst": ("About Anbox Cloud", "https://discourse.ubuntu.com/t/anbox-cloud-overview/17802", "explanation/landing.rst", 1),
    "explanation/applications.rst": ("About applications", "https://discourse.ubuntu.com/t/managing-applications/17760", "explanation/landing.rst", 3),
    "explanation/application-streaming.rst": ("About application streaming", "https://discourse.ubuntu.com/t/streaming-android-applications/17769", "explanation/landing.rst", 9),
    "explanation/benchmarking.rst": ("About benchmarking", "https://discourse.ubuntu.com/t/benchmarking-a-deployment/17770", "explanation/landing.rst", 8),
    "explanation/clustering.rst": ("About clustering", "https://discourse.ubuntu.com/t/capacity-planning/17765", "explanation/landing.rst", 6),
    "explanation/containers.rst": ("About containers", "https://discourse.ubuntu.com/t/managing-containers/17763", "explanation/landing.rst", 5),
    "explanation/gpu-support.rst": ("About GPU support", "https://discourse.ubuntu.com/t/gpu-support/17768", "explanation/landing.rst", 7),
    "explanation/porting-issues.rst": ("Issues when porting apps", "https://discourse.ubuntu.com/t/usecase-port-android-application-to-anbox-cloud/17776", "explanation/landing.rst", 10),
    "howto/troubleshoot.rst": ("Troubleshoot Anbox Cloud", "https://discourse.ubuntu.com/t/anbox-cloud-faq/17837", "howto/landing.rst", 9),
    "howto/aar/configure.rst": ("Configure an AAR", "https://discourse.ubuntu.com/t/configure-an-aar/24319", "howto/application/landing.rst", 8),
    "howto/aar/deploy.rst": ("Deploy an AAR", "https://discourse.ubuntu.com/t/installation-application-registry/17749", "howto/application/landing.rst", 7),
    "howto/aar/revoke.rst": ("Revoke an AAR client", "https://discourse.ubuntu.com/t/revoke-an-aar-client/24320", "howto/application/landing.rst", 9),
    "howto/application/create.rst": ("Create an application", "https://discourse.ubuntu.com/t/create-an-application/24198", "howto/application/landing.rst", 1),
    "howto/application/delete.rst": ("Delete an application", "https://discourse.ubuntu.com/t/delete-an-application/24199", "howto/application/landing.rst", 5),
    "howto/application/landing.rst": ("Manage applications", "https://discourse.ubuntu.com/t/manage-applications/24333", "howto/landing.rst", 4),
    "howto/application/list.rst": ("List applications", "https://discourse.ubuntu.com/t/list-applications/24200", "howto/application/landing.rst", 6),
    "howto/application/resources.rst": ("Configure available resources", "https://discourse.ubuntu.com/t/configure-available-resources/24960", "howto/application/landing.rst", 4),
    "howto/application/test.rst": ("Test your application", "https://discourse.ubuntu.com/t/usecase-application-testing/17775", "howto/application/landing.rst", 10),
    "howto/application/update.rst": ("Update an application", "https://discourse.ubuntu.com/t/update-an-application/24201", "howto/application/landing.rst", 3),
    "howto/application/virtual-devices.rst": ("Create a virtual device", "https://discourse.ubuntu.com/t/virtual-devices/19069", "howto/application/landing.rst", 11),
    "howto/application/wait.rst": ("Wait for an application", "https://discourse.ubuntu.com/t/wait-for-an-application/24202", "howto/application/landing.rst", 2),
    "howto/cluster/landing.rst": ("Manage cluster nodes", "https://discourse.ubuntu.com/t/manage-cluster-nodes/24334", "howto/landing.rst", 8),
    "howto/cluster/scale-down.rst": ("Scale down a LXD cluster", "https://discourse.ubuntu.com/t/scale-down-a-lxd-cluster/24323", "howto/cluster/landing.rst", 2),
    "howto/cluster/scale-up.rst": ("Scale up a LXD cluster", "https://discourse.ubuntu.com/t/scale-up-a-lxd-cluster/24322", "howto/cluster/landing.rst", 1),
    "howto/container/access.rst": ("Access a container", "https://discourse.ubuntu.com/t/container-access/17772", "howto/container/landing.rst", 3),
    "howto/container/backup-and-restore.rst": ("Back up and restore application data", "https://discourse.ubuntu.com/t/back-up-and-restore-application-data/24183", "howto/container/landing.rst", 9),
    "howto/container/delete.rst": ("Delete a container", "https://discourse.ubuntu.com/t/delete-a-container/24325", "howto/container/landing.rst", 6),
    "howto/container/expose-services.rst": ("Expose services", "https://discourse.ubuntu.com/t/expose-services-on-a-container/24326", "howto/container/landing.rst", 4),
    "howto/container/geographic-location.rst": ("Configure geographic location", "https://discourse.ubuntu.com/t/usecase-container-configuration/17782", "howto/container/landing.rst", 8),
    "howto/container/landing.rst": ("Work with containers", "https://discourse.ubuntu.com/t/work-with-containers/24335", "howto/landing.rst", 5),
    "howto/container/launch.rst": ("Launch a container", "https://discourse.ubuntu.com/t/launch-a-container/24327", "howto/container/landing.rst", 1),
    "howto/container/list.rst": ("List containers", "https://discourse.ubuntu.com/t/list-containers/24328", "howto/container/landing.rst", 7),
    "howto/container/logs.rst": ("View the container logs", "https://discourse.ubuntu.com/t/view-the-container-logs/24329", "howto/container/landing.rst", 5),
    "howto/container/wait.rst": ("Wait for a container", "https://discourse.ubuntu.com/t/wait-for-a-container/24330", "howto/container/landing.rst", 2),
    "howto/install/customise.rst": ("Customise the installation", "https://discourse.ubuntu.com/t/installation-customizing/17747", "howto/install/landing.rst", 2),
    "howto/install/deploy-juju.rst": ("Deploy with Juju", "https://discourse.ubuntu.com/t/install-with-juju/17744", "howto/install/landing.rst", 1),
    "howto/install/high-availability.rst": ("Enable High Availability", "https://discourse.ubuntu.com/t/high-availability/17754", "howto/install/landing.rst", 3),
    "howto/install/landing.rst": ("Install Anbox Cloud", "https://discourse.ubuntu.com/t/install-anbox-cloud/24336", "howto/landing.rst", 1),
    "howto/install/validate.rst": ("Validate the deployment", "https://discourse.ubuntu.com/t/validation/20329", "howto/install/landing.rst", 4),
    "howto/manage/ams-access.rst": ("Control AMS remotely", "https://discourse.ubuntu.com/t/managing-ams-access/17774", "howto/manage/landing.rst", 5),
    "howto/manage/images.rst": ("Manage images", "https://discourse.ubuntu.com/t/managing-images/17758", "howto/manage/landing.rst", 2),
    "howto/manage/landing.rst": ("Manage Anbox Cloud", "https://discourse.ubuntu.com/t/manage-anbox-cloud/24337", "howto/landing.rst", 3),
    "howto/manage/logs.rst": ("View logs", "https://discourse.ubuntu.com/t/managing-logs/17771", "howto/manage/landing.rst", 4),
    "howto/manage/web-dashboard.rst": ("Use the web dashboard", "https://discourse.ubuntu.com/t/web-dashboard/20871", "howto/manage/landing.rst", 1),
    "howto/monitor/grafana.rst": ("Use Grafana", "https://discourse.ubuntu.com/t/monitoring-grafana/17787", "howto/monitor/landing.rst", 2),
    "howto/monitor/install.rst": ("Install the monitoring stack", "https://discourse.ubuntu.com/t/monitoring-installation/17786", "howto/monitor/landing.rst", 1),
    "howto/monitor/landing.rst": ("Monitor Anbox Cloud", "https://discourse.ubuntu.com/t/monitor-anbox-cloud/24338", "howto/landing.rst", 6),
    "howto/monitor/nagios.rst": ("Use Nagios", "https://discourse.ubuntu.com/t/monitoring-nagios/17788", "howto/monitor/landing.rst", 3),
    "howto/stream/access.rst": ("Access the stream gateway", "https://discourse.ubuntu.com/t/managing-stream-gateway-access/17784", "howto/stream/landing.rst", 1),
    "howto/stream/client-side-keyboard.rst": ("Use a client-side keyboard", "https://discourse.ubuntu.com/t/integrate-a-client-side-virtual-keyboard/23643", "howto/stream/landing.rst", 5),
    "howto/stream/landing.rst": ("Implement streaming", "https://discourse.ubuntu.com/t/implement-streaming/24332", "howto/landing.rst", 7),
    "howto/stream/native-client.rst": ("Implement a native client", "https://discourse.ubuntu.com/t/implement-android-native-streaming-client/21833", "howto/stream/landing.rst", 2),
    "howto/stream/oob-data.rst": ("Exchange OOB data", "https://discourse.ubuntu.com/t/exchange-out-of-band-data/21834", "howto/stream/landing.rst", 4),
    "howto/stream/web-client.rst": ("Implement a web-based client", "https://discourse.ubuntu.com/t/implement-web-based-streaming-client/21835", "howto/stream/landing.rst", 3),
    "howto/update/control.rst": ("Control updates", "https://discourse.ubuntu.com/t/control-updates/24959", "howto/update/landing.rst", 1),
    "howto/update/landing.rst": ("Update your installation", "https://discourse.ubuntu.com/t/update-your-installation/24331", "howto/landing.rst", 2),
    "howto/update/upgrade-anbox.rst": ("Upgrade Anbox Cloud", "https://discourse.ubuntu.com/t/upgrading-from-previous-versions/17750", "howto/update/landing.rst", 3),
    "howto/update/upgrade-appliance.rst": ("Upgrade the appliance", "https://discourse.ubuntu.com/t/upgrade-anbox-cloud-appliance/24186", "howto/update/landing.rst", 2),
    "reference/ams-configuration.rst": ("AMS configuration", "https://discourse.ubuntu.com/t/ams-configuration/20872", "reference/landing.rst", 7),
    "reference/ams-http-api.rst": ("AMS HTTP API", "https://discourse.ubuntu.com/t/ams-rest-api-reference/17801", "reference/api-reference.rst", 1),
    "reference/anbox-http-api.rst": ("Anbox HTTP API", "https://discourse.ubuntu.com/t/anbox-http-api-reference/17819", "reference/api-reference.rst", 2),
    "reference/api-reference.rst": ("API reference", "https://discourse.ubuntu.com/t/api-reference/24339", "reference/landing.rst", 3),
    "reference/application-manifest.rst": ("Application manifest", "https://discourse.ubuntu.com/t/application-manifest/24197", "reference/landing.rst", 8),
    "reference/instance-types.rst": ("Instance types", "https://discourse.ubuntu.com/t/instance-types-reference/17764", "reference/landing.rst", 4),
    "reference/perf-benchmarks.rst": ("Performance benchmarks", "https://discourse.ubuntu.com/t/performance-benchmarks/24709", "reference/landing.rst", 9),
    "reference/platforms.rst": ("Anbox platforms", "https://discourse.ubuntu.com/t/anbox-platforms/18733", "reference/landing.rst", 5),
    "reference/prometheus.rst": ("Prometheus metrics", "https://discourse.ubuntu.com/t/prometheus-metrics/19521", "reference/landing.rst", 6),
    "reference/provided-images.rst": ("Provided images", "https://discourse.ubuntu.com/t/provided-images/24185", "reference/landing.rst", 1),
    "reference/sdks.rst": ("Anbox Cloud SDKs", "https://discourse.ubuntu.com/t/anbox-cloud-sdks/17844", "reference/landing.rst", 2),
    "tutorial/getting-started-dashboard.rst": ("Getting started (web dashboard)", "https://discourse.ubuntu.com/t/getting-started-with-anbox-cloud-web-dashboard/24958", "tutorial/landing.rst", 2),
    "tutorial/getting-started.rst": ("Getting started (CLI)", "https://discourse.ubuntu.com/t/getting-started/17756", "tutorial/landing.rst", 3),
    "tutorial/installing-appliance.rst": ("Installing the appliance", "https://discourse.ubuntu.com/t/install-appliance/22681", "tutorial/landing.rst", 1),
    "tutorial/landing.rst": ("Tutorials", "na", "index.rst", 1),
    "howto/landing.rst": ("How-to guides", "na", "index.rst", 2),
    "reference/landing.rst": ("Reference", "na", "index.rst", 3),
    "explanation/landing.rst": ("Explanation", "na", "index.rst", 4),
    "anbox/landing.rst": ("Anbox Cloud", "na", "index.rst", 5)
    }
