import yaml

replace_string = "<!-- GENERATED_TABLE "

tables = {}

with open("ref/ams-configuration.yaml", 'r') as f:

    config = yaml.safe_load(f)

    # Loop through the different sections/tables in the YAML file
    # and generate a table for each
    for which, options in config.items():
        table = "| Name | Type | Default |  Description            |\n"
        table += "|------|------|---------|-------------------------|\n"

        for option, info in sorted(options.items()):
            table += "| `" + str(option) + "` "
            table += "| " + str(info['type']) + " "
            table += "| " + str(info['default']) + " "
            table += "| " + str(info['description']) + " |\n"

        tables[which] = table

# Open the template file for reading and the Markdown file for writing
with open("ref/ams-configuration.tmpl.md", 'r') as infile, open("ref/ams-configuration.md", 'w') as outfile:
    outfile.write("<!-- DO NOT EDIT THIS FILE. IT IS GENERATED AUTOMATICALLY. -->\n")
    outfile.write("<!-- Edit ams-configuration.tmpl.md and ams-configuration.yaml instead. -->\n\n")

    for line in infile:
        # Replace the "<!-- GENERATED_TABLE xxx -->" lines with the table for "xxx"
        if line.startswith(replace_string):
            which = line[len(replace_string):].replace("-->","").strip()
            outfile.write(tables[which])
        # Copy the other lines from the template
        else:
            outfile.write(line)
